export const Text =
  " por voluntad propia y debidamente informado (a) consiento tomar la radiografía dígital y/o estudios diagnósticos de emergencia/urgencia a ser realizado durante la pandemia de COVID-19.";

export const Text1 =
  "Yo acepto Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce imperdiet elementum turpis, vitae mattis nunc sollicitudin ut. Nullam feugiat odio et nulla ultrices, eu mattis augue aliquam. Integer interdum at leo in dapibus. Quisque posuere gravida justo eu aliquet. Sed sodales ligula sit amet est porta, eu luctus ligula aliquet. Nunc nisl odio, pellentesque nec accumsan dictum, malesuada sed ligula. Aliquam erat volutpat. Mauris volutpat nisi sed libero sollicitudin fermentum sed in arcu. Duis non tincidunt ipsum. In tincidunt, sem et pulvinar dignissim, justo tellus bibendum dui, quis placerat nibh mauris facilisis massa. Sed vulputate augue sem, eget placerat felis venenatis vitae. Morbi ornare semper feugiat. Suspendisse non accumsan leo. Etiam velit dui, vulputate at augue ut, molestie aliquam justo.";
export const Text2 =
  "Yo acepto Donec tincidunt augue id justo consectetur eleifend. Phasellus ut vehicula erat, id feugiat libero. Suspendisse felis sem, auctor sit amet metus ut, tristique eleifend mi. Donec interdum nibh orci, in pretium turpis viverra sed. Suspendisse potenti. Sed odio lacus, pharetra quis velit id, sollicitudin condimentum nisi. Aenean vel nulla imperdiet, consequat nisl eget, molestie nunc. Aenean congue metus sapien, posuere vestibulum massa pretium nec.";

export const Text3 =
  "Yo acepto Integer blandit pretium tristique. Sed sit amet tempor sem. Proin nulla nibh, sollicitudin eu eros accumsan, imperdiet hendrerit quam. Vivamus vehicula placerat dolor, vitae facilisis massa imperdiet vel. Vivamus sit amet consectetur felis, at porta eros. In in velit vehicula, aliquet elit rhoncus, viverra lectus. Nulla leo tortor, ullamcorper nec tincidunt at, molestie sed leo. Integer felis lacus, elementum tincidunt quam vitae, viverra fermentum nulla.";
